#!/usr/bin/env bash
# Bash script that install nginx web server
apt-get update -y
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start
