#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://bayona.me permanent;' /etc/nginx/sites-available/default
service nginx start
