#!/usr/bin/env bash
# This displays the storie of the file /etc/passwd.


FILE="/etc/passwd"
while IFS=":" read -r username password uid gid uidinfo home_d com_s
do
    echo "The user $username is part of the $gid gang, lives in $home_d and rides $com_s. $uid's place is protected by the passcode $password, more info about the user here: $uidinfo"
done < "$FILE"
