#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

a=1
while [ $a -lt 21 ]
do
    case $a in
	4)
	    echo $a
	    echo "bad luck from China"
	    ;;
	9)
	    echo $a
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo $a
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $a
	    ;;
	esac
    ((a++))
done
