#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

a=0
while [ $a -lt 20 ]
do
    echo $a
    if [ $a -eq 4 ]
    then
	echo "bad luck from China"
    elif [ $a -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $a -eq 17 ]
    then
	echo "bad luck from Italy"
    else
	echo $a
    fi
    ((a++))
done
